version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /usr/local/share/ca-certificates/app.com.crt:/etc/nginx/certs/app.com.crt
      - /usr/local/share/ca-certificates/app.com.key:/etc/nginx/certs/app.com.key

  nginx:
    image: nginx:1.19-alpine
    restart: always
    environment:
      - VIRTUAL_HOST=api.app.com
    volumes:
      - ./docker/dev/build/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${APP_API_PUBLIC_PATH}:/api/public

  php:
    restart: always
    build:
      context: .
      dockerfile: docker/dev/build/php/Dockerfile
    expose:
      - 9000
    volumes:
      - ${APP_API_PATH}:/api

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_VERSION=8.0.22
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
    volumes:
      - db:/var/lib/mysql

  node:
    restart: always
    build:
      context: .
      dockerfile: docker/dev/build/node/Dockerfile
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=app.com
      - HOST=0.0.0.0
    volumes:
      - ${APP_PATH}:/app

volumes:
  db:
